version: 2
updates:
  - package-ecosystem: nuget
    directory: / # Central package management, so Directory.Packages.props
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
