using System.Collections.Frozen;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace RomMBat.Core.Mapping;

/// <summary>
/// <c>data/retrobat/platforms.json</c>: RomM slug to an ordered list of RetroBat folders.
/// </summary>
/// <remarks>
/// Layer 3 of the resolution chain and nothing more. It is a seed with the seed's known
/// errors taken out, not an authority: a user override and a <c>fs_slug</c> match against
/// the live <c>es_systems.cfg</c> both outrank it, and where a slug names several folders
/// the first one the install actually has wins.
/// <para>
/// Embedded rather than copied, for the same reason the migrations are: a single-file
/// publish carries it and nothing has to resolve a path to find it.
/// </para>
/// </remarks>
public sealed class BundledPlatformMap
{
    private const string ResourceName = "RomMBat.Core.data.retrobat.platforms.json";

    private static readonly JsonSerializerOptions SerializerOptions = new(JsonSerializerDefaults.Web);

    private readonly FrozenDictionary<string, IReadOnlyList<string>> _platforms;
    private readonly FrozenDictionary<string, string> _requiresChoice;

    private BundledPlatformMap(
        FrozenDictionary<string, IReadOnlyList<string>> platforms,
        FrozenDictionary<string, string> requiresChoice)
    {
        _platforms = platforms;
        _requiresChoice = requiresChoice;
    }

    /// <summary>The shipped table, read once.</summary>
    public static BundledPlatformMap Bundled { get; } = LoadEmbedded();

    /// <summary>Every slug the table names.</summary>
    public IReadOnlyCollection<string> Slugs => _platforms.Keys;

    /// <summary>Reads a table from JSON. Tests use this; shipped code uses <see cref="Bundled"/>.</summary>
    public static BundledPlatformMap Parse(Stream json)
    {
        ArgumentNullException.ThrowIfNull(json);

        var document = JsonSerializer.Deserialize<PlatformMapDocument>(json, SerializerOptions)
            ?? throw new InvalidOperationException("platforms.json is empty.");

        return new BundledPlatformMap(
            document.Platforms.ToFrozenDictionary(
                pair => pair.Key,
                pair => (IReadOnlyList<string>)pair.Value,
                StringComparer.OrdinalIgnoreCase),
            document.RequiresExplicitChoice.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase));
    }

    /// <summary>The folders this slug may map to, best first. Empty when the table has no entry.</summary>
    public IReadOnlyList<string> Candidates(string? slug) =>
        slug is not null && _platforms.TryGetValue(slug, out var folders) ? folders : [];

    /// <summary>
    /// True when this slug must never resolve on its own.
    /// </summary>
    /// <remarks>
    /// <c>arcade</c> is the case that matters: which of its folders is correct depends on the
    /// romset a file came from, and arcade ROM names are romset-versioned, so nothing in the
    /// slug can settle it.
    /// </remarks>
    public bool RequiresExplicitChoice(string? slug, out string why)
    {
        why = string.Empty;
        return slug is not null && _requiresChoice.TryGetValue(slug, out why!);
    }

    private static BundledPlatformMap LoadEmbedded()
    {
        var assembly = typeof(BundledPlatformMap).Assembly;
        using var stream = assembly.GetManifestResourceStream(ResourceName)
            ?? throw new InvalidOperationException(
                $"'{ResourceName}' is missing from the assembly. It is embedded by RomMBat.Core.csproj "
                    + "and generated by tools/build-platform-map.py.");

        return Parse(stream);
    }

    private sealed class PlatformMapDocument
    {
        [JsonPropertyName("platforms")]
        public Dictionary<string, List<string>> Platforms { get; init; } = [];

        [JsonPropertyName("_requires_explicit_choice")]
        public Dictionary<string, string> RequiresExplicitChoice { get; init; } = [];
    }
}
