using RomMBat.Core.Content;
using Xunit;

namespace RomMBat.Tests;

public class ErasedSaveTests
{
    /// <summary>
    /// What ares/GameGear left on <c>Esc</c> for Sonic Chaos, a cartridge with no battery: 32 KB of
    /// nothing but <c>0xFF</c>.
    /// </summary>
    internal static byte[] ErasedRam(int length = 32 * 1024) => Enumerable.Repeat((byte)0xFF, length).ToArray();

    /// <summary>
    /// Defenders of Oasis's boot write, from generated bytes: erased apart from a header at
    /// <c>0x100</c>, which is where the game writes <c>Backup Ver0.84</c>.
    /// </summary>
    internal static byte[] RamWithHeader()
    {
        var ram = ErasedRam();
        "Backup Ver0.84"u8.CopyTo(ram.AsSpan(0x110));
        return ram;
    }

    [Fact]
    public void Nothing_but_0xff_is_erased_at_any_length()
    {
        Assert.True(ErasedSave.IsErased(ErasedRam()));
        Assert.True(ErasedSave.IsErased(ErasedRam(1)));
        Assert.True(ErasedSave.IsErased(ErasedRam(296_960)));
    }

    [Fact]
    public void One_written_byte_anywhere_is_a_save()
    {
        Assert.False(ErasedSave.IsErased(RamWithHeader()));

        var last = ErasedRam();
        last[^1] = 0xFE;
        Assert.False(ErasedSave.IsErased(last));
    }

    [Fact]
    public void An_empty_file_is_not_erased_ram()
    {
        // A zero-byte file is a separate question, answered per extension by empty_not_a_save.
        Assert.False(ErasedSave.IsErased([]));
    }

    [Fact]
    public void A_file_on_disk_is_read_through_and_a_missing_one_is_not_erased()
    {
        var path = Path.Combine(Path.GetTempPath(), $"rommbat-erased-{Guid.NewGuid():N}.ram");
        try
        {
            File.WriteAllBytes(path, ErasedRam());
            Assert.True(ErasedSave.IsErased(path));

            File.WriteAllBytes(path, RamWithHeader());
            Assert.False(ErasedSave.IsErased(path));
        }
        finally
        {
            File.Delete(path);
        }

        Assert.False(ErasedSave.IsErased(path));
    }
}
