using RomMBat.Core.Content;
using Xunit;

namespace RomMBat.Tests;

public class Ps1MemoryCardTests
{
    /// <summary>
    /// A card laid out the way the BIOS formats one, from generated bytes: the <c>MC</c> header
    /// frame and fifteen directory frames marked never used.
    /// </summary>
    internal static byte[] BlankCard()
    {
        var card = new byte[Ps1MemoryCard.CardBytes];
        card[0] = (byte)'M';
        card[1] = (byte)'C';

        for (var frame = 1; frame <= 15; frame++)
        {
            var at = frame * 128;
            card[at] = 0xA0;
            card[at + 8] = 0xFF;
            card[at + 9] = 0xFF;
        }

        return card;
    }

    /// <summary>A blank card with one save in block 1, named the way SotN names its save.</summary>
    internal static byte[] CardWithOneSave()
    {
        var card = BlankCard();
        card[128] = 0x51;
        "BASLUS-00067DRAX00"u8.CopyTo(card.AsSpan(128 + 10));
        card[8192] = (byte)'S';
        card[8193] = (byte)'C';
        return card;
    }

    [Fact]
    public void A_formatted_card_with_every_frame_never_used_is_blank()
    {
        Assert.True(Ps1MemoryCard.IsBlank(BlankCard()));
    }

    [Fact]
    public void A_card_holding_a_save_is_not_blank()
    {
        Assert.False(Ps1MemoryCard.IsBlank(CardWithOneSave()));
    }

    [Theory]
    [InlineData(0xA1)]
    [InlineData(0xA2)]
    [InlineData(0xA3)]
    public void A_card_whose_saves_were_deleted_in_the_game_is_not_blank(byte deleted)
    {
        var card = BlankCard();
        card[128 * 3] = deleted;

        Assert.False(Ps1MemoryCard.IsBlank(card));
    }

    [Fact]
    public void Bytes_without_the_card_header_are_not_a_blank_card()
    {
        var card = BlankCard();
        card[0] = 0;

        Assert.False(Ps1MemoryCard.IsBlank(card));
    }

    [Fact]
    public void A_file_of_any_other_length_is_not_a_blank_card()
    {
        var directory = Directory.CreateTempSubdirectory("rommbat-card-");

        try
        {
            var shorter = Path.Combine(directory.FullName, "short.srm");
            File.WriteAllBytes(shorter, BlankCard()[..8192]);
            Assert.False(Ps1MemoryCard.IsBlank(shorter));

            var exact = Path.Combine(directory.FullName, "exact.srm");
            File.WriteAllBytes(exact, BlankCard());
            Assert.True(Ps1MemoryCard.IsBlank(exact));
        }
        finally
        {
            directory.Delete(recursive: true);
        }
    }
}
