#!/usr/bin/env python3
"""Emit data/retrobat/bios.json: what RetroBat requires under bios/, per system.

RetroBat ships this data, and ships it in a form nothing can read. A real 8.2.0 install
carries no batocera-systems.json at all: the manifest is a .NET string resource inside
emulationstation/batocera-systems.exe, byte-identical to the vendored copy apart from a
trailing newline (tools/m5-probes/m5-probe1-manifest-in-install.py). So unlike
es_systems.cfg, there is no live copy to prefer, and RomMBat bundles the manifest instead.

The transform is deliberately thin, because the vendored file is the authority and a
generator that decided things would be a second authority that can disagree with it:

  * an empty md5 becomes null, which is a third state and not a missing file. 179 of the
    353 entries carry one, across 49 systems, and 28 systems have nothing else
  * the destination path is kept exactly as RetroBat writes it, relative to the RetroBat
    root, because that is the whole point of the manifest
  * two system keys are aliased to the RetroBat folder of the same system, below

Usage: python tools/build-bios-manifest.py [--check]
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REFERENCE = ROOT / "reference"
OUTPUT = ROOT / "data" / "retrobat" / "bios.json"

# The manifest is keyed by batocera system names, which is a third vocabulary beside
# es_systems.cfg's <name> and its <path> basename. 97 of the 99 keys are exactly a <path>
# basename; these two are not, and each names a system RetroBat does have under another
# folder. Checked by the assertion below, so a new divergence fails the build rather than
# silently dropping a system's firmware.
ALIASES = {
    "astrocde": "astrocade",
    "msx": "msx1",
}


def build() -> dict:
    manifest = json.loads((REFERENCE / "batocera-systems.json").read_text(encoding="utf-8"))
    known = {line.strip() for line in (REFERENCE / "systems_names.lst").read_text(encoding="utf-8").splitlines() if line.strip()}

    unresolved = sorted(key for key in manifest if key not in known and ALIASES.get(key) not in known)
    if unresolved:
        raise SystemExit(f"manifest keys that are no RetroBat system and have no alias: {unresolved}")

    stale = sorted(key for key in ALIASES if key in known)
    if stale:
        raise SystemExit(f"aliases for keys RetroBat now lists directly, so they should go: {stale}")

    systems = {}
    for key, body in sorted(manifest.items()):
        systems[key] = {
            "name": body.get("name", key),
            "folder": ALIASES.get(key, key),
            "files": [
                {"md5": entry["md5"].strip().lower() or None, "path": entry["file"]}
                for entry in body.get("biosFiles", [])
            ],
        }

    files = [file for system in systems.values() for file in system["files"]]

    return {
        "_comment": (
            "What RetroBat requires under bios/, per system, with the md5 to join RomM's "
            "firmware on and the exact destination path relative to the RetroBat root. An "
            "entry whose md5 is null is one RetroBat names no hash for: it can be neither "
            "found in RomM nor recognised on disk, and it is reported as unverifiable rather "
            "than as missing. 'folder' is the RetroBat system folder, which is the manifest "
            "key for 97 of the 99 systems. Generated by tools/build-bios-manifest.py from "
            "reference/batocera-systems.json; do not hand-edit."
        ),
        "_source": "RetroBat-Official/emulatorlauncher batocera-systems/Resources/batocera-systems.json",
        "_systems": len(systems),
        "_files": len(files),
        "_files_without_md5": sum(1 for file in files if file["md5"] is None),
        "_distinct_md5s": len({file["md5"] for file in files if file["md5"]}),
        "_aliases": ALIASES,
        "systems": systems,
    }


def main() -> int:
    document = build()
    rendered = json.dumps(document, indent=2, ensure_ascii=False) + "\n"

    if "--check" in sys.argv:
        # Compared as parsed JSON, not as bytes: Trunk's prettier owns the formatting of
        # everything under data/, and re-indenting the file is not drift. Content is.
        current = json.loads(OUTPUT.read_text(encoding="utf-8")) if OUTPUT.exists() else None
        if current != document:
            print(f"{OUTPUT.relative_to(ROOT)} is stale. Run tools/build-bios-manifest.py.")
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is up to date.")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(
        f"{OUTPUT.relative_to(ROOT)}: {document['_systems']} systems, {document['_files']} files, "
        f"{document['_distinct_md5s']} joinable md5s, {document['_files_without_md5']} with no hash."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
